import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import TopNav from '../components/navbar/TopNav'
import SwitchColor from '../components/Toggle'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav />
    </div>
  )
}

export default Home
